name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'ext/**'
      - 'gradle/**'
      - '*.gradle'
      - 'gradlew*'
      - '*.properties'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: |
          ./gradlew asD --no-daemon
          unzip -j ext/build/outputs/aar/ext-debug.aar classes.jar
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV

      - name: Upload built library
        uses: actions/upload-artifact@v4
        with:
          name: BenesseExtension@${{ env.commit }}
          path: classes.jar
